navigation:
  - name  : Articles
    url   : /posts/
    weight: 1
  - name  : By Categories
    url   : /categories/
    weight: 2
  - name  : Projects
    url   : /projects/
    weight: 3
  - name  : Contact
    url   : /contact/
    weight: 100