baseURL: /
canonifyURLs: false
copyright: © 2007-Today / Setyo. All rights reserved.
disableHugoGeneratorInject: true
enableEmoji: true
enableRobotsTXT: true
footnoteReturnLinkContents: ↩
languageCode: id
languageName: Indonesian
MetaDataFormat: yaml
paginate: 5
theme: sty
title: nsetyo.id

author:
    name: Setyo Nugroho
    email: setyo@pm.me
markup:
    highlight:
        codeFences: true
        guessSyntax: true
        noClasses: false
menus:
    navigation:
        - name: Archive
          url: /posts/
          weight: 1
        - name: About
          url: https://youtube.com/watch?v=dQw4w9WgXcQ
          weight: 2
minify:
    minifyOutput: true
params:
    canonicalUrl: https://nsetyo.id
    description:
        Catatan nsetyo! Sebuah catatan pribadi, tidak kurang, apalagi lebih.
