version: '3'
### Service Network ############################################################
services:
    node-setup:
        command: bash -c 'npm install'
        image: nsetyo-id
        volumes:
            - ./.bashrc:/root/.bashrc
            - ./.cache/npm:/root/.npm
            - ./:/var/www/
        healthcheck:
            test: bash -c '[ -f node_modules/.bin/postcss ]'
            interval: 1s
            timeout: 60s
    www:
        image: nsetyo-id
        depends_on:
            node-setup:
                condition: service_healthy
        build:
            dockerfile: ./.dockerfile
            context: .
            args:
                - NODEJS_VERSION=16.15
                - HUGO_CHECKSUM=f930fcc5559337233d24de3704a09b877a6cd29449241b69e111e10b24f6e200
                - HUGO_VERSION=0.99.1
        command:
            ${HUGO_COMMAND:-hugo server --bind 0.0.0.0 --liveReloadPort 443}
        networks:
            - public
        expose:
            - 1313
        volumes:
            - ./.bashrc:/root/.bashrc
            - ./.cache/npm:/root/.npm
            - ./.git:/var/www/.git
            - ./.vscode-server/node:/root/.vscode-server
            - ./:/var/www/
            - ${WORKSPACE_GPG_DIR:-/home/nsetyo/.gnupg}:/root/.gnupg
            - ${WORKSPACE_SSH_DIR:-/home/nsetyo/.ssh}:/root/.ssh
        labels:
            caddy.reverse_proxy: '{{upstreams 1313}}'
            caddy: nsetyo.localhost
networks:
    public:
        external: true
        name: caddy
