image: debian:latest

variables:
  HUGO_VERSION : "0.58.2"
  HUGO_CHECKSUM: "7ac65f7ee6dd30f6c3667e0c2fa22a0034c0945e0614447c6b2b4d7795d192d2"
  HUGO_ENV     : "production"

stages:
  - test

before_script:
  - apt update && apt install --no-install-recommends -yqq curl ca-certificates
  - curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_$HUGO_VERSION\_Linux-64bit.tar.gz
  - echo "$HUGO_CHECKSUM  hugo.tar.gz" | sha256sum -c
  - tar xzvf hugo.tar.gz && cp ./hugo /usr/bin/hugo
  - hugo version
  - curl -sL https://deb.nodesource.com/setup_12.x | bash -
  - apt update && apt install --no-install-recommends -yqq openssl nodejs git
  - npm install -g postcss-cli autoprefixer postcss-import && npm install

test:
  stage : test
  script: hugo --minify -d public
